########################################################################
##               Main Analysis from Diffusion Simulation              ##
##                  Multivariate Normal Distribution                  ##
##                              One Factor                            ##
##                           Between Subject                          ## 
########################################################################

## ---------------------------------------------------------------------
## Preparation
## ---------------------------------------------------------------------

source("ddm_simulation_bs.R")

library(MASS)
library(visdat)
library(dplyr)
library(tidyverse)
library(data.table)
library(rtdists)
library(afex)
library(emmeans)
library(fitdistrplus)
library(truncdist)
library(parallel)

library(tmvtnorm)
library(purrr)
library(xtable)

library(lme4)

## set wd to the directory to save the files

## -----------------------------------------------------------------------
## NAMING
## -----------------------------------------------------------------------

## name_dataframe(wd, distribution, model, design, n, size, reruns)
## name the file name of the dataframe to be saved

##           wd: the directory to save the files
## distribution: uni (univariate) or multi (multivariate)
##        model: data generation model, log or ddm
##       design: experimental design, bs (between-subject) or rm (repeated-measure)
##            n: number of participants per group/condition
##         size: trials per participant
##       reruns: number of simulations

name_dataframe <- function(wd, distribution, model, design, n, size, reruns){
  properties <- c(wd, "/",
                  distribution, "_", 
                  model, "_", 
                  design, "_", 
                  n, "pp", 
                  size, "tr_",
                  reruns, "runs.rda")
  
  # combine all single characters into one character vector to be the file name
  newname <- paste(properties, collapse = "")
  
  # cat() and print() both make sure that the output is shown in the console
  print(newname)
  newname
}

## -----------------------------------------------------------------------
## Parameter Values Matrix
## -----------------------------------------------------------------------

## Create data for simulation ############################################
## mu: a, st0, sv, t0, v, z
mu <- c(2.8, 0.2, 1, 0.3, -0.6, 0.50)

## sigma
load("sigma.rda")

## Create lists with all combinations of DDM parameters ##################

## v2 ranges from 0 to 4 by 0.5 step
## For each v2, v1 ranges within [0:8]
combos <- expand.grid(v1 = seq(0, 8, by = 1),
                      v2 = seq(0, 4, by = 0.5))
## 9*9 = 81 rows

combos_all <- combos %>% 
  mutate(a = rep(2.8, nrow(combos)),    # fixed a
         st0 = rep(0.2, nrow(combos)),  # fixed st0
         sv = combos$v2,                # varied sv
         t0 = rep(0.3, nrow(combos)),   # fixed t0
         v = combos$v1,                 # varied v
         z = rep(0.5, nrow(combos)))    # fixed z

## Keep the parameters in the original order
combos_all$v1 <- NULL 
combos_all$v2 <- NULL 

colnames(combos_all) <- NULL

## Create a variable containing 81 lists
## each list containing a set of parameters with one combination of v & sv
combos_use <- t(split(t(combos_all), 
                      rep(1:ncol(t(combos_all)), each = nrow(t(combos_all)))
                      )
                )

## ---------------------------------------------------------------------
## MVT: Between-Subject
## ---------------------------------------------------------------------

## Main Function #######################################################

## simulate_data_mvt_bs(pp, size, reruns, cores = 2)

## INPUT
##  sigma: rda file with drift diffusion parameters from an original model
##     mu: combinations of possible parameter values of DDM
##     pp: number of participants [per group]
##   size: number or trials per participant
## reruns: number of simulations
##         [NOTE] reruns = 1, 81 simulations will be produced for all combinations of parameters of DDM
##  cores: the number of cores to run simulations simultaneously

## OUTPUT
##          aov_p: p-value generated by ANOVA
##          glm_p: p-value generated by GLM
##     diff_props: difference in upper response proportion between groups
## mean_prop_real: mean proportion of success for both groups combined 
##                 * converge with [prob in logistic simulation] for large samples
##        g1_prop: upper response proportion for group 1
##        g2_prop: upper response proportion for group 2
##           size: number of trials per participant
##          pp_g1: number of participants in group1, same as pp
##          pp_g2: number of participants in group2, same as pp
## DDM parameters: mean and sd for a, st0, sv, t0, v, z
##           data: each simulation of data

simulate_data_mvt_bs <- function(pp, size, reruns, cores = 2){
  
  # mcmapply(FUN, ..., MoreArgs)
  # apply FUN taking each element of ... argument (each combination of DDM parameters)
  # reruns_bs(mu, sigma, size, pp, reruns)
  sim_mvt <- mcmapply(reruns_bs, mu = combos_use,
                      MoreArgs = list(sigma = sigma,
                                      pp = pp,
                                      size = size,
                                      reruns = reruns),
                      mc.cores = cores)
  
  # combine R objects by rows
  # one row contains the results from one simulation
  sim_mvt <- bind_rows(sim_mvt)
  
  file_name <- name_dataframe(wd = wd,
                              distribution = 'multi', 
                              model = 'ddm', 
                              design = 'bs', 
                              n = pp, 
                              size = size, 
                              reruns = reruns)
  # save(sim_mvt, file = file_name,
  #      compress = "xz")
  sim_mvt
}

########################################################################

## RUN THE SIMULATION MVT100
#  30 participants per group
#  100 trials per participant
#  v (drift rate) ~ [0, 1, 2, 3, 4, 5, 6, 7, 8]
#  sv (intertrial variability of drift rate) ~ [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4]

pp_mvt100_bs <- 30
size_mvt100_bs <- 100

## 1000 Runs 
mvt100_bs_1000 <- simulate_data_mvt_bs(pp = pp_mvt100_bs,
                                       size = size_mvt100_bs,
                                       reruns = 1000, cores = 12)

########################################################################

## RUN THE SIMULATION MVT1
#  30 participants per group
#  1 trial per participant
#  v (drift rate) ~ [0, 1, 2, 3, 4, 5, 6, 7, 8]
#  sv (intertrial variability of drift rate) ~ [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4]

pp_mvt1_bs <- 30
size_mvt1_bs <- 1

## 1000 Runs 
mvt1_bs_1000 <- simulate_data_mvt_bs(pp = pp_mvt1_bs,
                                     size = size_mvt1_bs,
                                     reruns = 1000, cores = 12)


## -----------------------------------------------------------------------
## DIFFUSION SIMULATION: REPEATED-MEASURE
## -----------------------------------------------------------------------




