########################################################################
##               Main Analysis from Diffusion Simulation              ##
##                  Multivariate Normal Distribution                  ##
##                              One Factor                            ##
##                           Between Subject                          ## 
########################################################################

## ---------------------------------------------------------------------
## Preparation
## ---------------------------------------------------------------------

source("./ddm_simulation_bs.R")

library(MASS)
library(visdat)
library(dplyr)
library(tidyverse)
library(data.table)
library(rtdists)
library(afex)
library(emmeans)
library(fitdistrplus)
library(truncdist)
library(parallel)

library(tmvtnorm)
library(purrr)
library(xtable)

library(lme4)

## set wd to the directory to save the files
wd <- "./results"

## -----------------------------------------------------------------------
## NAMING
## -----------------------------------------------------------------------

## name_dataframe(wd, model, design, n, size, reruns)
## name the file name of the dataframe to be saved

##           wd: the directory to save the files
##        model: data generation model, log or ddm
##       design: experimental design, bs (between-subject) or rm (repeated-measure)
##            n: number of participants per group/condition
##         size: trials per participant
##       reruns: number of simulations

name_dataframe <- function(wd, model, design, n, size, reruns){
  properties <- c(wd, "/",
                  model, "_", 
                  design, "_", 
                  n, "pp", 
                  size, "tr_",
                  reruns, "runs.rda")
  
  # combine all single characters into one character vector to be the file name
  newname <- paste(properties, collapse = "")
  
  # cat() and print() both make sure that the output is shown in the console
  print(newname)
  newname
}

## -----------------------------------------------------------------------
## Parameter Values Matrix
## -----------------------------------------------------------------------

## Load mean and covariance matrix for simulation #######################
load("./parameters/mu.rda")
load("./parameters/cov.rda")
cov
mu 
#     vnl    an     z   t0n    sv   st0
#   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
# 1 0.975  2.01 0.542 0.280 0.639 0.279
mu <- c(0.975, 2.01, 0.542, 0.280, 0.639, 0.279)

## Create lists with all combinations of DDM parameters ##################

## v ranges from 0 to 8 by step = 1
## For each v, sv ranges from 0 to 4 by step = 0.5
combos <- expand.grid(v_tmp = seq(0, 8, by = 1),
                      sv_tmp = seq(0, 4, by = 0.5))
## 9 * 9 = 81 combinations

combos_all <- combos %>% 
  mutate(v = v_tmp,                      # varied v
         a = rep(mu[2], nrow(combos)),   # fixed a
         z = rep(mu[3], nrow(combos)),   # fixed z
         t0 = rep(mu[4], nrow(combos)),  # fixed t0
         sv = sv_tmp,                    # varied sv
         st0 = rep(mu[5], nrow(combos))  # fixed st0
         )

## Keep the parameters in the original order
combos_all$v1 <- NULL 
combos_all$v2 <- NULL 

colnames(combos_all) <- NULL

## Create a variable containing 81 lists
## each list containing a set of parameters with one combination of v & sv
combos_use <- t(split(t(combos_all), 
                      rep(1:ncol(t(combos_all)), each = nrow(t(combos_all)))
                      )
                )

## ---------------------------------------------------------------------
## MVT: Between-Subject
## ---------------------------------------------------------------------

## Main Function #######################################################

## simulate_data_bs(pp, size, reruns, cores = 2)

## INPUT
##  sigma: rda file with drift diffusion parameters from an original model
##     mu: combinations of possible parameter values of DDM
##     pp: number of participants [per group]
##   size: number or trials per participant
## reruns: number of simulations
##         [NOTE] reruns = 1, 81 simulations will be produced for all combinations of parameters of DDM
##  cores: the number of cores to run simulations simultaneously

## OUTPUT
##          aov_p: p-value generated by ANOVA
##          glm_p: p-value generated by GLM
##         glmm_p: p-value generated by GLMM
##     diff_props: difference in upper response proportion between groups
## mean_prop_real: mean proportion of success for both groups combined 
##                 * converge with [prob in logistic simulation] for large samples
##        g1_prop: upper response proportion for group 1
##        g2_prop: upper response proportion for group 2
##           size: number of trials per participant
##          pp_g1: number of participants in group1, same as pp
##          pp_g2: number of participants in group2, same as pp
## DDM parameters: mean and sd for a, st0, sv, t0, v, z
##           data: each simulation of data
##        glm_obj: glm model
##       glmm_obj: glmm model

simulate_data_bs <- function(pp, size, reruns, cores = 2){
  
  # mcmapply(FUN, ..., MoreArgs)
  # apply FUN taking each element of ... argument (each combination of DDM parameters)
  # reruns_bs(mu, sigma, size, pp, reruns)
  sim_mvt <- mcmapply(reruns_bs, mu = combos_use,
                      MoreArgs = list(sigma = sigma,
                                      pp = pp,
                                      size = size,
                                      reruns = reruns),
                      mc.cores = cores)
  
  # combine R objects by rows
  # one row contains the results from one simulation
  sim_mvt <- bind_rows(sim_mvt)
  
  file_name <- name_dataframe(wd = wd,
                              model = 'ddm', 
                              design = 'bs', 
                              n = pp, 
                              size = size, 
                              reruns = reruns)
  # save(sim_mvt, file = file_name,
  #      compress = "xz")
  sim_mvt
}

########################################################################

## simulate_data_bs(pp, size, reruns, cores = 2)

## RUN THE SIMULATION BS100_1V
#  30 participants per group
#  100 trials per participant
#  v (drift rate) ~ [0, 1, 2, 3, 4, 5, 6, 7, 8]
#  sv (intertrial variability of drift rate) ~ [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4]

pp_bs100 <- 30
size_bs100 <- 100

## 1000 Runs 
ddm_bs100_1000 <- simulate_data_bs(pp = pp_bs100,
                                   size = size_bs100,
                                   reruns = 1000, cores = 12)

########################################################################

## RUN THE SIMULATION BS1_1V
#  30 participants per group
#  1 trial per participant
#  v (drift rate) ~ [0, 1, 2, 3, 4, 5, 6, 7, 8]
#  sv (intertrial variability of drift rate) ~ [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4]

pp_bs1 <- 30
size_bs1 <- 1

## 1000 Runs 
ddm_bs1_1000 <- simulate_data_bs(pp = pp_bs1,
                                 size = size_bs1,
                                 reruns = 1000, cores = 12)









