########################################################################
##               Main Analysis from Logistic Simulation               ##
##                              One Factor                            ##
##                           Between Subject                          ##
########################################################################

library(MASS)
library(visdat)
library(tidyverse)
library(data.table)
library(readxl)
library(rtdists)
library(xtable)
library(afex)
library(emmeans)
library(dplyr)
library(fitdistrplus)
library(truncdist)
library(parallel)

source("logistic_simulation_bs.R")

## set wd to the directory to save files

## -----------------------------------------------------------------------
## NAMING
## -----------------------------------------------------------------------

## name_dataframe(wd, distribution, model, design, n, size, reruns)
## name the file name of the dataframe to be saved

##           wd: the directory to save the files
##        model: data generation model, log or ddm
##       design: experimental design, bs (between-subject) or rm (repeated-measure)
##            n: number of participants
##         size: trials per participant
##       reruns: number of the data sets to be simulated

name_dataframe <- function(wd, distribution, model, design, n, size, reruns){
  properties <- c(wd, "/",
                  model, "_", 
                  design, "_id_", 
                  n, "pp", 
                  size, "tr", "_",
                  reruns, "runs.rda")
  # combine all single characters into one character vector to be the filename
  newname <- paste(properties, collapse = "")
  
  # cat() and print() both make sure that the output is shown in the console
  print(newname)
  newname
}

## -----------------------------------------------------------------------
## LOGISTIC SIMULATION: BETWEEN-SUBJECT
## -----------------------------------------------------------------------

## simulate_logistic_bs(n, size, reruns, cores = 2)

## Parameters
##      n: number of participants
##         [NOTE] Don't need to divide by 2, the total number of participants
##   size: number or trials per participant
##     sd: standard deviation of individual variances around prob
## reruns: number of runs
##         [NOTE] If reruns = 1, 10 data sets will be produced for 10 probabilities
##  cores: the number of cores to run simultaneously

## Output
##          aov_p: p-value generated by ANOVA
##          glm_p: p-value generated by GLM
##         glmm_p: p-value generated by GLMM
##     diff_props: difference in proportion of successes between groups
## mean_prop_real: mean proportion of success for both groups combined 
##                 * meant to converge with prob for large samples
##        g1_prop: proportion of successes for group 1
##        g2_prop: proportion of successes for group 2
##              n: number of participants
##           size: number or trials per participant
##          probs: probability of success for an experiment (same for both groups)
##     glm_object: glm model
##    glmm_object: glmm model

simulate_logistic_bs <- function(n, size, sd, reruns, cores = 2){
  # set 10 values of the probability, ranging from 0.5 to 0.975 by 0.05 pace
  probs <- seq(0.5, 0.975, by = 0.05)
  
  # mapply(FUN, ..., MoreArgs) 
  # apply FUN to each element of the ... argument (i.e., each value of prob)
  # MoreArgs defines other arguments to FUN 
  # rerun_logistic_bs(n, size, prob, reruns)
  simulated_data <- mcmapply(rerun_logistic_bs, prob = probs,
                             MoreArgs = list(n = n, 
                                             size = size, 
                                             sd = sd,
                                             reruns = reruns), 
                             mc.cores = cores)
  
  # combine R objects by rows
  # one row contains the results from one simulation
  # n = reruns rows for one prob value
  
  simulated_data <- bind_rows(simulated_data)
  
  file_name <- name_dataframe(wd = wd,
                              model = 'log', 
                              design = 'bs', 
                              n = n, 
                              size = size, 
                              reruns = reruns)
  save(simulated_data, file = file_name, compress = "xz")
  simulated_data 
}

########################################################################

## RUN THE SIMULATION BS100
#  30 participants per group
#  100 trials per participant
#  probability of success [0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95]
#  reruns the simulation for 1000 times

n_bs100 <- 30
size_bs100 <- 100

## 1000 Runs
simulate_logistic_bs(n = n_bs100, size = n_bs100, reruns = 1000, sd = 0.5, cores = 12)

########################################################################

## RUN THE SIMULATION BS1
#  30 participants per group
#  1 trial per participant
#  probability of success [0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95]
#  reruns the simulation for 1000 times

n_bs1 <- 30
size_bs1 <- 1

## 1000 Runs
simulate_logistic_bs(n = n_bs1, size = n_bs1, reruns = 1000, sd = 0.5, cores = 12)







